export const SCATTER_USER = 'SCATTER_USER';
export const FETCH_COIN_MARKET_CAP_DATA = 'FETCH_COIN_MARKET_CAP_DATA';
export const SEARCH_TERM = 'SEARCH_TERM';
export const SEARCHED_DATA = 'SEARCHED_DATA';
export const HEXMAP_DATA = 'HEXMAP_DATA';
